CREATE TABLE USERS (
    ID RAW(16) PRIMARY KEY,
    EMAIL VARCHAR2(200) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(200) NOT NULL,
    DISPLAY_NAME VARCHAR2(120) NOT NULL,
    ROLE VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE PRODUCTS (
    ID RAW(16) PRIMARY KEY,
    NAME VARCHAR2(200) NOT NULL,
    CATEGORY VARCHAR2(120) NOT NULL,
    KCAL_100G NUMBER(10,2),
    CO2_PER_UNIT NUMBER(10,3),
    BARCODE VARCHAR2(64) UNIQUE
);

CREATE TABLE PRODUCT_IMPACT (
    PRODUCT_ID RAW(16) PRIMARY KEY,
    CO2_PER_UNIT NUMBER(10,3),
    WATER_L NUMBER(10,2),
    ORIGIN VARCHAR2(120),
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT FK_IMPACT_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

CREATE TABLE PRODUCT_NUTRITION (
    ID RAW(16) PRIMARY KEY,
    PRODUCT_ID RAW(16) NOT NULL,
    NUTRI_KEY VARCHAR2(80) NOT NULL,
    NUTRI_VALUE VARCHAR2(120) NOT NULL,
    CONSTRAINT FK_NUTRITION_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

CREATE TABLE SCAN_HISTORY (
    ID RAW(16) PRIMARY KEY,
    USER_ID RAW(16) NOT NULL,
    PRODUCT_ID RAW(16) NOT NULL,
    SCANNED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    SOURCE VARCHAR2(60),
    CONSTRAINT FK_SCAN_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_SCAN_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

CREATE TABLE FAVORITES (
    USER_ID RAW(16) NOT NULL,
    PRODUCT_ID RAW(16) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_FAVORITES PRIMARY KEY (USER_ID, PRODUCT_ID),
    CONSTRAINT FK_FAVORITE_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_FAVORITE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);
